/**
 * main.c
 *
 * Test harness for spo2_pipeline.c: reads IR/Red captures from a flat CSV
 * (generated by preprocess_rd.py from inputs/rd.csv) and runs the SpO2
 * computation pipeline on each one, comparing against the reference value
 * and reporting error metrics.
 *
 * Expected format of the input CSV (one row per capture):
 *   n_samples, IR_0, ..., IR_{n_samples-1}, Red_0, ..., Red_{n_samples-1},
 *   SpO2_ref, rd_row, rd_column
 * n_samples is the actual length of the raw capture and varies row to row
 * (it is not a fixed constant); it must not exceed SPO2_MAX_N_SAMPLES
 * (see spo2_pipeline.h).
 *
 * It also writes a results CSV with the actual output of the C algorithm
 * for every measurement, with columns:
 *   row, column, valid, R, SNR, PI, SQI, SpO2_ref, SpO2_C, HR_bpm
 * so it can be cross-referenced with the original inputs/rd.csv dataset
 * (rd_row/rd_column identify the source cell in that dataset).
 *
 * Self-contained file (includes spo2_pipeline.c directly): it's enough to
 * compile/run this file alone, without linking anything else.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* The implementation is included (not just the header) so this file is
 * self-contained: VS Code's "Run"/"Debug" runner buttons only compile the
 * active file, without linking other .c files in the project. */
#include "spo2_pipeline.c"

/* A row holds n_samples + 2*n_samples values + SpO2_ref + rd_row + rd_column,
 * each up to ~12 characters (comma included); a generous margin is used,
 * sized to the largest capture the pipeline can handle. */
#define MAX_LINE (SPO2_MAX_N_SAMPLES * 2 * 16 + 64)
/* Maximum length of the source column name in rd.csv (e.g. "S3"). */
#define MAX_COLUMN_LEN 32

/**
 * Parses one line of the input CSV and fills the output arrays/values.
 *
 * The line is walked once with strtok, tokenizing on commas (or the
 * trailing carriage-return/newline): first n_samples itself, then the
 * n_samples IR values, then the n_samples Red values, then SpO2_ref,
 * rd_row and rd_column, in that fixed order (see the format documented at
 * the top of the file). strtok modifies "line" in place (replaces commas
 * with '\0'), which is why the input buffer can't be a string literal.
 *
 * @return 1 if the row has every expected field, 0 if the line is
 *         truncated/incomplete (e.g. a trailing blank line in the file,
 *         or n_samples exceeding SPO2_MAX_N_SAMPLES); in that case the
 *         caller must discard the row and keep going.
 */
static int parse_row(char *line, float *ir, float *red, int *n_samples,
                      float *ref, int *rd_row, char *rd_column)
{
    /* First token: start tokenizing the freshly read line. */
    char *tok = strtok(line, ",\r\n");

    /* n_samples: the actual length of this capture, read from the row
     * itself rather than assumed to be a fixed constant. */
    if (!tok)
        return 0;
    *n_samples = atoi(tok);
    if (*n_samples <= 0 || *n_samples > SPO2_MAX_N_SAMPLES)
        return 0;
    tok = strtok(NULL, ",\r\n");

    /* Infrared (IR) channel: the next n_samples fields of the row. */
    for (int i = 0; i < *n_samples; i++)
    {
        /* Ran out of tokens before filling the array: malformed row. */
        if (!tok)
            return 0;
        /* strtof instead of atof: parses straight into a float, avoiding
         * atof's implicit double->float cast; NULL means we don't need
         * the pointer to the first unparsed character. */
        ir[i] = strtof(tok, NULL);
        /* Advance to the next comma-separated field. */
        tok = strtok(NULL, ",\r\n");
    }
    /* Red channel: the next n_samples fields, same pattern as above. */
    for (int i = 0; i < *n_samples; i++)
    {
        if (!tok)
            return 0;
        red[i] = strtof(tok, NULL);
        tok = strtok(NULL, ",\r\n");
    }
    /* Reference SpO2 (ground-truth value from the reference pulse oximeter). */
    if (!tok)
        return 0;
    *ref = strtof(tok, NULL);

    /* Source row index in rd.csv, to cross-reference results with the dataset. */
    tok = strtok(NULL, ",\r\n");
    if (!tok)
        return 0;
    *rd_row = atoi(tok);

    /* Source column name in rd.csv (e.g. "S3"), same purpose as rd_row. */
    tok = strtok(NULL, ",\r\n");
    if (!tok)
        return 0;
    /* Bounded copy: leaves room for the manual '\0' below, so a token
     * longer than the buffer can't overflow rd_column. */
    strncpy(rd_column, tok, MAX_COLUMN_LEN - 1);
    rd_column[MAX_COLUMN_LEN - 1] = '\0';

    /* All fields were present: row is well-formed. */
    return 1;
}

int main(int argc, char **argv)
{
    /* Paths are configurable from the command line: ./main [input] [output];
     * with no arguments, the project's default paths are used instead. */
    const char *path = (argc > 1) ? argv[1] : "inputs/spo2_captures.csv";
    const char *out_path = (argc > 2) ? argv[2] : "outputs/spo2_results.csv";

    /* Open the input CSV for reading; bail out early if it doesn't exist. */
    FILE *f = fopen(path, "r");
    if (!f)
    {
        fprintf(stderr, "Could not open '%s'\n", path);
        return 1;
    }

    /* Open (or create/truncate) the output CSV for writing. */
    FILE *fout = fopen(out_path, "w");
    if (!fout)
    {
        fprintf(stderr, "Could not create '%s'\n", out_path);
        /* Close the already-open input file before returning: avoid leaking
         * the file descriptor on this early-exit path. */
        fclose(f);
        return 1;
    }
    /* Header of the results CSV; its column order must match the fprintf
     * further below that writes each data row. */
    fprintf(fout, "row,column,valid,R,SNR,PI,SQI,SpO2_ref,SpO2_C,HR_bpm\n");

    /* Static buffers (not on the stack): same no-dynamic-allocation
     * convention as spo2_pipeline.c (deterministic, embedded-friendly
     * memory footprint), and they're reused across iterations with no
     * need to reinitialize them each time. */
    static char line[MAX_LINE];
    static float ir[SPO2_MAX_N_SAMPLES];
    static float red[SPO2_MAX_N_SAMPLES];
    static char rd_column[MAX_COLUMN_LEN];

    /* Consume the header line of the input CSV before the data loop. */
    if (!fgets(line, sizeof(line), f)) /* skip header */
    {
        /* fgets returned NULL on the very first read: the file has no
         * header line at all, i.e. it's empty. */
        fprintf(stderr, "Empty file: '%s'\n", path);
        fclose(f);
        fclose(fout);
        return 1;
    }

    /* Global counters: total rows read, captures accepted by the pipeline,
     * and a breakdown of rejection reasons (see Spo2Status in
     * spo2_pipeline.h) for the final summary. */
    int n_total = 0, n_ok = 0;
    int n_low_ac = 0, n_low_snr = 0, n_r_range = 0, n_bad_n_samples = 0;
    /* Error accumulators (predicted SpO2 vs. reference), computed only over
     * accepted captures, used to compute the global RMSE and MAE at the end. */
    double sum_sq_err = 0.0, sum_abs_err = 0.0;

    /* Per-level RMSE accumulators, indexed by integer SpO2_ref level (0-100):
     * lets us see whether error grows at the extremes (very low or very
     * high SpO2) instead of only looking at the global RMSE. */
    #define N_LEVELS 101
    static int level_n[N_LEVELS];
    static double level_sum_sq[N_LEVELS];

    /* Main loop: one iteration per row of the input CSV. */
    while (fgets(line, sizeof(line), f))
    {
        /* Per-row outputs of parse_row(); declared inside the loop since
         * they only need to live for the current iteration. */
        float ref;
        int rd_row, n_samples;
        /* Truncated or blank line (e.g. a trailing blank line in the
         * file): discard it without counting it in n_total or the stats. */
        if (!parse_row(line, ir, red, &n_samples, &ref, &rd_row, rd_column))
            continue;

        /* Row was well-formed: count it towards the total processed. */
        n_total++;

        /* Run the C SpO2 pipeline on this capture: computes the ratio R,
         * quality metrics (SNR, PI, SQI) and heart rate, and validates the
         * capture against the configured thresholds. n_samples comes from
         * the row itself, so captures of different lengths are handled
         * without any change to this call. */
        float R, snr, pi, hr_bpm;
        uint8_t sqi;
        Spo2Status status = spo2_compute_R(ir, red, n_samples, &R, &snr, &pi, &hr_bpm, &sqi);
        /* Boolean shorthand for "the pipeline accepted this capture". */
        int valid = (status == SPO2_OK);
        /* SpO2 estimate from R via the calibration curve, computed even
         * when the capture isn't valid (still logged, so rejected captures
         * can be inspected in the output CSV too). */
        float spo2 = roundf(spo2_predict(R));

        /* Write the results row; field order must match the header
         * written above. */
        fprintf(fout, "%d,%s,%s,%.9g,%.9g,%.9g,%u,%.9g,%.9g,%.9g\n",
                rd_row, rd_column, valid ? "True" : "False", (double)R,
                (double)snr, (double)pi, (unsigned)sqi, (double)ref,
                (double)spo2, (double)hr_bpm);

        /* Only SPO2_OK captures feed the error metrics; rejected ones are
         * only tallied by rejection reason, without affecting RMSE/MAE
         * (there's no point measuring the error of an estimate the
         * algorithm itself already flagged as unreliable). */
        switch (status)
        {
        case SPO2_OK:
        {
            /* Accepted capture: count it and accumulate its error. */
            n_ok++;
            double err = (double)spo2 - (double)ref;
            sum_sq_err += err * err;
            sum_abs_err += fabs(err);

            /* lround instead of truncating: SpO2_ref may come with decimals
             * from the reference pulse oximeter, so it's rounded to the
             * nearest integer level for the per-level RMSE breakdown. */
            int level = (int)lround((double)ref);
            /* Guard against out-of-range levels before indexing the arrays. */
            if (level >= 0 && level < N_LEVELS)
            {
                level_n[level]++;
                level_sum_sq[level] += err * err;
            }
            break;
        }
        case SPO2_ERR_LOW_AC:
            /* AC amplitude too low to extract a ratio: tally and move on. */
            n_low_ac++;
            break;
        case SPO2_ERR_LOW_SNR:
            /* Heart-rate peak SNR below SPO2_SNR_THRESHOLD: tally and move on. */
            n_low_snr++;
            break;
        case SPO2_ERR_R_RANGE:
            /* R outside [SPO2_R_MIN, SPO2_R_MAX]: tally and move on. */
            n_r_range++;
            break;
        case SPO2_ERR_N_SAMPLES:
            /* n_samples too small to leave a usable window, or larger than
             * SPO2_MAX_N_SAMPLES: tally and move on. */
            n_bad_n_samples++;
            break;
        }
    }
    /* Done reading/writing: release both file handles before reporting. */
    fclose(f);
    fclose(fout);

    /* Percentage of rows that passed validation, guarding against a
     * division by zero when the input file had no usable rows. */
    double pct_ok = (n_total > 0) ? (100.0 * n_ok / n_total) : 0.0;

    /* ─── Console summary ───────────────────────────────────────────── */

    printf("\nResults over %d captures:\n", n_total);
    /* Only print error metrics if at least one capture was accepted;
     * otherwise rmse/mae below would divide by zero. */
    if (n_ok > 0)
    {
        /* Level-by-level RMSE breakdown: helps spot whether the error is
         * concentrated in a particular SpO2 range (e.g. severe hypoxia,
         * where there's usually less calibration data). */
        printf("\nRMSE by SpO2 level:\n");
        for (int level = 0; level < N_LEVELS; level++)
        {
            /* Skip levels with no accepted samples: nothing to report. */
            if (level_n[level] == 0)
                continue;
            double rmse_level = sqrt(level_sum_sq[level] / level_n[level]);
            printf(" %3d%%  n=%3d  RMSE = %.2f %%\n", level, level_n[level], rmse_level);
        }

        /* Global RMSE/MAE across every accepted capture. */
        double rmse = sqrt(sum_sq_err / n_ok);
        double mae = sum_abs_err / n_ok;
        printf("\nRMSE = %.2f %%\n", rmse);
        printf("MAE  = %.2f %%\n\n", mae);
    }

    /* Finally: how many rows were processed, how many passed, and a
     * breakdown of why the rejected ones failed. */
    printf("Captures processed          = %d samples\n", n_total);
    printf("Valid captures              = %d (%.1f %%) \n", n_ok, pct_ok);
    printf(" Rejected: low AC           = %d\n", n_low_ac);
    printf(" Rejected: low SNR          = %d\n", n_low_snr);
    printf(" Rejected: R out of range   = %d\n", n_r_range);
    printf(" Rejected: bad n_samples    = %d\n\n", n_bad_n_samples);

    printf("Results written to '%s'\n\n", out_path);

    return 0;
}
